### ISSUE TITLE
flutter debug can not show a new editor window

### ISSUE THREAD

**Issue by kyrosle** [gjsjohnmurray/searchable-debug-console#1]
hello, i use vscode to do flutter development, it seem the new debug editor window cannot appear when i run the debug, however, it show after i cancel the debug session

**Comment by gjsjohnmurray** [comment]
I am unfamiliar with Flutter development. Is this the extension you are using?

https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

When you debug does any text appear in the DEBUG CONSOLE view (which I will refer to as DC), which by default is a tab on the VS Code Panel?

The Searchable Debug Console (SDC) extension is supposed to replicate to its editor anything that a debugger such as the Flutter extension might write to DC. SDC should open an editor as soon as a debug session writes its first output to DC

If you are seeing text appear in DC but not in an SDC editor, please paste screenshots (even better, a short GIF recording, e.g. using https://gifcap.dev/) into your response on the GH web page.

**Comment by SharbelOkzan** [comment]
In my case, the editor is being opened and I see one line of logs dumped into it, but not the rest of my logs.
<img width="1512" alt="Screenshot 2024-02-25 at 17 50 03" src="https://github.com/gjsjohnmurray/searchable-debug-console/assets/89970141/6e79eb32-271f-4c2f-9662-810795e0c853">

Note: The extension might be still listening to the logs but not showing them, because when I stop the debugging session, I see two new lines added to the editor:

```
** [2/25/2024, 5:48:38 PM] - Stopping session <app_name> (iPhone 15 Pro Max)
** [2/25/2024, 5:48:38 PM] - Exiting session <app_name> (iPhone 15 Pro Max): code=0, signal=undefined
```

> I am unfamiliar with Flutter development. Is this the extension you are using?https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

Yes, that's the extension in my case

**Comment by gjsjohnmurray** [comment]
The first line of output comes from this extension, as do the ones appearing when you stop debugging.

Your screenshot shows two "Debug session XXX" tabs? Was the one suffixed "Untitled-1" left over from a previous debug run? Or does it contain the missing debug console output.

**Comment by SharbelOkzan** [comment]
> Was the one suffixed "Untitled-1" left over from a previous debug run? Or does it contain the missing debug console output.

@gjsjohnmurray just a leftover from a previous trial. It had similar content.

**Comment by gjsjohnmurray** [comment]
Do you still see this problem with the latest version of my extension?
