### ISSUE TITLE
It would be great if you could search for keywords directly through ctrl + f like in the terminal.

### ISSUE THREAD

**Issue by seryte** [gjsjohnmurray/searchable-debug-console#2]

**Comment by gjsjohnmurray** [comment]
Can't you already do this, in the "Debug session XXX" tab that this extension duplicates DEBUG CONSOLE tab output into?

**Comment by seryte** [comment]
> Can't you already do this, in the "Debug session XXX" tab that this extension duplicates DEBUG CONSOLE tab output into?

It can open a temporary file to record debug logs, but it feels too cumbersome, and when there is a breakpoint recovery, it no longer records

**Comment by gjsjohnmurray** [comment]
Sounds like you want https://github.com/microsoft/vscode/issues/4338
