### ISSUE TITLE
All files are closed at launch

### ISSUE THREAD

**Issue by Arndt-MBE** [gjsjohnmurray/searchable-debug-console#5]
When launching a debug process, the redirection file is opened, but all other files currently opened in the editor are closed.

**Comment by gjsjohnmurray** [comment]
I don't know why that should be happening for you. Does it also occur with a temporary profile? You can create one with the `Profiles: Create a Temporary Profile` command from Command Palette.

If it does, please post a short video of what you're seeing. One way is to use https://gifcap.dev/

Make sure you don't include any confidential information.

**Comment by Arndt-MBE** [comment]
Thank you for your suggestions, John. I found it easier to use the terminal instead of the debug output, so, for now, I don't use the extension any more.

**Comment by gjsjohnmurray** [comment]
I was able to reproduce this. Today's v0.0.3 should fix it.

**Comment by Arndt-MBE** [comment]
I have reinstalled the extension and will try to give feedback soon.
@gjsjohnmurray Thank you for looking into this.

**Comment by Arndt-MBE** [comment]
I can confirm that opening and closing of the searchable pseudo-file no longer affects other open file tabs.
