### ISSUE TITLE
When I installed, started seeing variables eval inside the editor. Uninstalled your extension but this behaviour continues. How to fix?

### ISSUE THREAD

**Issue by asapsmc** [gjsjohnmurray/searchable-debug-console#6]
Hello, 

I installed your extension (VSCode 1.91.1 in macos Sonoma), and started seeing variable evals inline in the editor view. Just uninstalled your extension but this behaviour continues. How may I fix this?

**Comment by gjsjohnmurray** [comment]
I'm not aware of anything this extension does which could cause that.

What is your `debug.inlineValues` setting?

**Comment by asapsmc** [comment]
It was 'auto'. Now I forced it to 'off'. But I have never changed this setting and also never had inline value shown in the editor, so I supposed it was this extension that changed this behaviour.

**Comment by gjsjohnmurray** [comment]
I have no idea how the extension could have done that. Anyway, glad you have resolved it.
